apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Eso01/end-end-Project"
    targetRevision: HEAD
    path: password-generator
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true