FROM python:3.9-slim

WORKDIR /app

COPY requirements.reverse.txt .
RUN pip install --no-cache-dir -r requirements.reverse.txt

COPY src/reverse.py .

CMD ["uvicorn", "reverse:app", "--host", "0.0.0.0", "--port", "5001"]
