replicaCount: 3

namespace: python-app-ns

images:
  passwordGenerator:
    repository: eso001/password-generator
    tag: 790132d
    pullPolicy: Always
  reverseService:
    repository: eso001/reverse-service
    tag: 790132d
    pullPolicy: Always

service:
  name: password-generator
  password:
    port: 8080
    targetPort: 5000
  
  reverse:
    port: 80
    targetPort: 5001

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: app.local
      
      paths:
        - path: /generate-password
          pathType: Prefix
          backend:
            service:
             name: service-password
             port: 
               number: 80    # explicitly defined here
        - path: /reverse-word
          pathType: Prefix
          backend:
            service:
             name: service-reverse
             port: 
               number: 80

  tls:
    - secretName: app-tls
      hosts:
        - app.local
